name = "rasid-web-app"
compatibility_date = "2024-01-01"

[build]
command = "flutter build web --release"

[build.upload]
format = "service-worker"

[[build.upload.rules]]
type = "ESModule"
globs = ["**/*.js"]

[site]
bucket = "./build/web"
